export const jobCategories = [
  { en: "Cleaner", sw: "Msafishaji" },
  { en: "House Cleaner", sw: "Msafishaji Nyumbani" },
  { en: "Office Cleaner", sw: "Msafishaji Ofisini" },
  { en: "Public Space Cleaner", sw: "Msafishaji Eneo la Umma" },
  { en: "Sweeper", sw: "Mfagia" },
  { en: "Street Sweeper", sw: "Mfagia Barabara" },
  { en: "Toilet Cleaner", sw: "Msafishaji Choo" },
  { en: "Laundry Assistant", sw: "Msaidizi Dobi" },
  { en: "Clothes Ironer", sw: "Mpiga Pasi" },
  { en: "Dish Washer", sw: "Mosha Vyombo" },
  { en: "Car Washer", sw: "Mosha Magari" },
  { en: "Motorcycle Washer", sw: "Mosha Pikipiki" },
  { en: "Trash Collector", sw: "Mkusanyaji Takataka" },
  { en: "Construction Helper", sw: "Msaidizi Ujenzi" },
  { en: "Mason Assistant", sw: "Msaidizi Mfundi Mawe" },
  { en: "Cement Mixer", sw: "Mchanganyaji Saruji" },
  { en: "Brick Carrier", sw: "Mbebaji Matofali" },
  { en: "Site Security Helper", sw: "Msaidizi Ulinzi Uwanja" },
  { en: "Fence Digger", sw: "Mchimbaji Ua" },
  { en: "Roof Repair Assistant", sw: "Msaidizi Ukarabati Paa" },
  { en: "Painter's Assistant", sw: "Msaidizi Mpaka Rangi" },
  { en: "Plumber", sw: "Fundi Mabomba" },
  { en: "Electrician", sw: "Fundi Umeme" },
  { en: "Tailor", sw: "Mshonaji" },
  { en: "Seamstress", sw: "Mshonaji wa Kike" },
  { en: "Carpenter", sw: "Seremala" },
  { en: "Mechanic - Car", sw: "Fundi Magari" },
  { en: "Mechanic - Motorcycle", sw: "Fundi Pikipiki" },
  { en: "Mechanic - Bicycle", sw: "Fundi Baiskeli" },
  { en: "Painter", sw: "Mpaka Rangi" },
  { en: "Sign Painter", sw: "Mpaka Rangi Vibao" },
  { en: "Tiler", sw: "Fundi Vigae" },
  { en: "Roofer", sw: "Fundi Mapaa" },
  { en: "Welder", sw: "Mwunganishaji" },
  { en: "DJ", sw: "DJ" },
  { en: "Sound Assistant", sw: "Msaidizi Sauti" },
  { en: "Phone Repair Technician", sw: "Fundi Simu" },
  { en: "TV Repair Technician", sw: "Fundi Televisheni" },
  { en: "Fridge Technician", sw: "Fundi Friji" },
  { en: "Shoe Repair - Fundi Viatu", sw: "Fundi Viatu" },
  { en: "Hairdresser", sw: "Msusi Nywele" },
  { en: "Barber", sw: "Kinyozi" },
  { en: "Henna Artist", sw: "Fundi Hina" },
  { en: "Makeup Artist", sw: "Fundi Vipodozi" },
  { en: "Makeup Artist (Mobile)", sw: "Fundi Vipodozi (Mzunguko)" },
  { en: "Hair Braider (Home Service)", sw: "Msokotaji Nywele (Nyumbani)" },
  { en: "Massage Therapist (Mobile)", sw: "Fundi Massage (Mzunguko)" },
  { en: "Babysitter", sw: "Mlezi Mtoto" },
  { en: "House Help", sw: "Msaidizi Nyumbani" },
  { en: "Nanny", sw: "Mlezi" },
  { en: "Cook", sw: "Mpishi" },
  { en: "Cook Assistant", sw: "Msaidizi Mpishi" },
  { en: "Elder Care", sw: "Mlezi Wazee" },
  { en: "Pet Sitter", sw: "Mlezi Wanyamapori" },
  { en: "Home Tutor (Basic)", sw: "Mwalimu Nyumbani (Msingi)" },
  {
    en: "Private Tutor",
    sw: "Mwalimu Binafsi",
  },
  { en: "Event Usher", sw: "Muongozaji Hafla" },
  { en: "Event Waiter", sw: "Mtumishi Hafla" },
  { en: "Waitress", sw: "Mtumishi wa Kike" },
  { en: "Catering Assistant", sw: "Msaidizi Utunzaji Chakula" },
  { en: "Tent Setup Crew", sw: "Timu Uwekaji Mahema" },
  { en: "Chair Setup Crew", sw: "Timu Uwekaji Viti" },
  { en: "Table Setup Crew", sw: "Timu Uwekaji Meza" },
  { en: "Bouncer", sw: "Mlinda Mlango" },
  { en: "MC (Master of Ceremony)", sw: "Mzungumzaji Mkuu" },
  { en: "Event Cleaner", sw: "Msafishaji Hafla" },
  { en: "Light Controller", sw: "Mdhibiti Mwanga" },
  { en: "Photographer - Event", sw: "Mpiga Picha - Hafla" },
  { en: "Photographer - Street", sw: "Mpiga Picha - Barabara" },
  { en: "Street Performer", sw: "Mchezaji Barabara" },
  { en: "Traditional Dancer", sw: "Mchezaji Ngoma" },
  { en: "Promotion Agent", sw: "Wakala Utangazaji" },
  { en: "Brand Ambassador", sw: "Balozi Chapa" },
  { en: "Flyer Distributor", sw: "Mgawaji Vipeperushi" },
  { en: "Poster Paster", sw: "Mbandikaji Mabango" },
  { en: "Sales Booth Worker", sw: "Mfanyakazi Kibanda Mauzo" },
  { en: "Street Vendor", sw: "Muuzaji Barabara" },
  { en: "Chips Seller", sw: "Muuzaji Chipsi" },
  { en: "Fruit Seller", sw: "Muuzaji Matunda" },
  { en: "Juice Maker", sw: "Mtengenezaji Juisi" },
  { en: "Roasted Maize Seller", sw: "Muuzaji Mahindi Mchele" },
  { en: "Balloon Seller", sw: "Muuzaji Puto" },
  { en: "Ice Cream Seller", sw: "Muuzaji Aiskrimu" },
  { en: "Mandazi Seller", sw: "Muuzaji Mandazi" },
  { en: "Chapati Seller", sw: "Muuzaji Chapati" },
  { en: "Water Seller", sw: "Muuzaji Maji" },
  { en: "Airtime Seller", sw: "Muuzaji Mitandao" },
  { en: "Scratch Card Seller", sw: "Muuzaji Kadi za Mchezo" },
  { en: "Mobile Accessories Seller", sw: "Muuzaji Vifaa vya Simu" },
  { en: "WhatsApp Seller", sw: "Muuzaji WhatsApp" },
  { en: "Shop Attendant", sw: "Mtumishi Duka" },
  { en: "Cashier", sw: "Mweka Fedha" },
  { en: "Online Seller Assistant", sw: "Msaidizi Muuzaji Mtandaoni" },
  { en: "TikTok Promoter", sw: "Mtangazaji TikTok" },
  { en: "Facebook Promoter", sw: "Mtangazaji Facebook" },
  { en: "WhatsApp Group Admin", sw: "Msimamizi Kikundi WhatsApp" },
  { en: "TikTok Video Editor", sw: "Mhariri Video TikTok" },
  { en: "Canva Designer", sw: "Mbunifu Canva" },
  { en: "Caption Writer", sw: "Mwandishi Manukuu" },
  { en: "Survey Filler", sw: "Mjaza Utafiti" },
  { en: "Ad Clicker", sw: "Mbonyezi Matangazo" },
  { en: "Transcriber", sw: "Mwandishi Maongezi" },
  { en: "Voice-over Artist", sw: "Fundi Sauti" },
  { en: "Photo Editor", sw: "Mhariri Picha" },
  { en: "Short Video Uploader", sw: "Mpakizi Video Fupi" },
  { en: "Content Commenter", sw: "Mtoaji Maoni" },
  { en: "Errand Runner", sw: "Mfanyakazi Ujumbe" },
  { en: "Package Delivery", sw: "Mpekezaji Vifurushi" },
  { en: "Food Delivery", sw: "Mpekezaji Chakula" },
  { en: "Gas Delivery", sw: "Mpekezaji Gesi" },
  { en: "Document Delivery", sw: "Mpekezaji Hati" },
  { en: "Motorcycle Rider (Boda)", sw: "Mwenendeshaji Pikipiki (Boda)" },
  { en: "Bicycle Courier", sw: "Mjumbe Baiskeli" },
  { en: "Tuk-tuk Driver", sw: "Dereva Tuk-tuk" },
  { en: "Private Driver", sw: "Dereva Binafsi" },
  { en: "Pickup Driver", sw: "Dereva Pickup" },
  { en: "Airport Driver", sw: "Dereva Uwanja wa Ndege" },
  { en: "Parking Assistant", sw: "Msaidizi Maegesho" },
  { en: "Valet", sw: "Msaidizi Gari" },
  { en: "Farm Worker", sw: "Mfanyakazi Shamba" },
  { en: "Planter", sw: "Mpandaji" },
  { en: "Weeder", sw: "Mng'oaji Magugu" },
  { en: "Harvester", sw: "Mvunaji" },
  { en: "Goat Herder", sw: "Mchungaji Mbuzi" },
  { en: "Cow Feeder", sw: "Mlishaji Ng'ombe" },
  { en: "Chicken Keeper", sw: "Mlezi Kuku" },
  { en: "Egg Collector", sw: "Mkusanyaji Mayai" },
  { en: "Farm Cleaner", sw: "Msafishaji Shamba" },
  { en: "Fence Builder", sw: "Mjenzi Ua" },
  { en: "Water Carrier", sw: "Mbebaji Maji" },
  { en: "Beekeeper Assistant", sw: "Msaidizi Mlezi Nyuki" },
  { en: "Fish Pond Cleaner", sw: "Msafishaji Bwawa la Samaki" },
  { en: "Manual Brick Maker", sw: "Mtengenezaji Matofali" },
  { en: "Firewood Chopper", sw: "Mkataji Kuni" },
  { en: "Coal Seller", sw: "Muuzaji Makaa" },
  { en: "Charcoal Bag Filler", sw: "Mjaza Mifuko ya Mkaa" },
  { en: "Queue Helper", sw: "Msaidizi Foleni" },
  { en: "Line Holder", sw: "Mshikaji Nafasi" },
  { en: "Reminder Caller", sw: "Mpigaji Simu za Ukumbusho" },
  { en: "Alarm Setter", sw: "Mwekaji Kengele" },
  { en: "Gate Closer", sw: "Mfungaji Lango" },
  { en: "Street Sign Holder", sw: "Mshikaji Kibao Barabara" },
  { en: "Umbrella Holder", sw: "Mshikaji Mwavuli" },
  { en: "Cemetery Helper", sw: "Msaidizi Makaburi" },
  { en: "Grave Digger", sw: "Mchimbaji Kaburi" },
  { en: "Local Guide", sw: "Mwongozaji wa Mitaa" },
  { en: "Tour Guide (Village)", sw: "Mwongozaji (Kijiji)" },
  { en: "Stand-in Service (Line)", sw: "Huduma ya Kusimama (Foleni)" },
  { en: "Garbage Sorter", sw: "Mpangaji Takataka" },
  { en: "Sack Filler", sw: "Mjaza Magunia" },
  { en: "Street Marketer", sw: "Mwuza Barabara" },
  { en: "Mobile Kiosk Attendant", sw: "Mtumishi Kiosk ya Kuzunguka" },
  { en: "Popcorn Maker", sw: "Mtengenezaji Popcorn" },
  { en: "Online Commenter", sw: "Mtoaji Maoni Mtandaoni" },
  { en: "Mobile Notification Sender", sw: "Mtumaji Arifa za Simu" },
  { en: "SMS Blaster", sw: "Mtumaji SMS Nyingi" },
  { en: "Door-to-door Marketer", sw: "Mwuza Nyumba kwa Nyumba" },
  { en: "Table Seller", sw: "Muuzaji Meza" },
  { en: "Street Table Guard", sw: "Mlinzi Meza Barabara" },
  { en: "Borehole Water Seller", sw: "Muuzaji Maji ya Kisima" },
  { en: "Well Cleaner", sw: "Msafishaji Kisima" },
  { en: "Street Kid Support", sw: "Msaidizi Watoto wa Mitaa" },
  { en: "Charity Volunteer (Paid)", sw: "Mjitolee Hisani (Malipo)" },
  { en: "Pet Feeder", sw: "Mlishaji Wanyamapori" },
  { en: "Bird Cage Cleaner", sw: "Msafishaji Tundu la Ndege" },
  { en: "Hen Seller", sw: "Muuzaji Kuku" },
  { en: "Egg Seller", sw: "Muuzaji Mayai" },
  { en: "Market Porter", sw: "Mchukuzi Sokoni" },
  { en: "Bus Conductor", sw: "Kondakta" },
  { en: "Vendor Assistant", sw: "Msaidizi Muuzaji" },
  { en: "Auction Helper", sw: "Msaidizi Mnada" },
  { en: "Crowd Control Helper", sw: "Msaidizi Udhibiti Umati" },
  { en: "Trolley Pusher", sw: "Msukumaji Trolley" },
  { en: "Baggage Carrier", sw: "Mbebaji Mizigo" },
  { en: "Water Drummer", sw: "Mpigaji Ngoma ya Maji" },
  { en: "Coal Stove Fixer", sw: "Mkarabati Jiko la Makaa" },
  { en: "Pot Repairer", sw: "Mkarabati Vyungu" },
  { en: "Clay Pot Seller", sw: "Muuzaji Vyungu vya Udongo" },
  { en: "Spoon Seller", sw: "Muuzaji Vijiko" },
  { en: "Mobile Soap Seller", sw: "Muuzaji Sabuni (Mzunguko)" },
  { en: "Shoe Polisher", sw: "Msuguzi Viatu" },
  { en: "On-call Security Guard", sw: "Askari wa Simu" },
  { en: "Car Watchman", sw: "Mlinzi Magari" },
  { en: "Night Guard", sw: "Askari wa Usiku" },
  { en: "Daytime Watch", sw: "Mlinzi wa Mchana" },
  { en: "Personal Shopper", sw: "Mnunuzi Binafsi" },
  { en: "Bag Packer", sw: "Mfungaji Mifuko" },
  { en: "Plastic Bottle Collector", sw: "Mkusanyaji Chupa za Plastiki" },
  { en: "Can Collector", sw: "Mkusanyaji Makopo" },
  { en: "Scrap Collector", sw: "Mkusanyaji Taka za Chuma" },
  { en: "Bottle Washer", sw: "Mosha Chupa" },
  { en: "Dish Rental Attendant", sw: "Mtumishi Ukodishaji Vyombo" },
  { en: "Tent Rental Assistant", sw: "Msaidizi Ukodishaji Mahema" },
  { en: "Container Loader", sw: "Mpakiaji Kontena" },
  { en: "Truck Loader", sw: "Mpakiaji Lori" },
  { en: "Mini-truck Helper", sw: "Msaidizi Lori Dogo" },
  { en: "Food Server", sw: "Mtumishi Chakula" },
  { en: "Local Cook (Nyama Choma)", sw: "Mpishi wa Mitaa (Nyama Choma)" },
  { en: "Fish Fryer", sw: "Mkaangaji Samaki" },
  { en: "Public Toilet Assistant", sw: "Msaidizi Choo cha Umma" },
  { en: "Toilet Paper Seller", sw: "Muuzaji Karatasi za Choo" },
  { en: "Bus Stop Guide", sw: "Mwongozaji Kituo cha Basi" },
  { en: "Lost & Found Assistant", sw: "Msaidizi Kupotea na Kupatikana" },
  { en: "Car Battery Jumper", sw: "Mwashaji Betri za Gari" },
  { en: "Street Phone Charger", sw: "Mchaji Simu Barabara" },
  { en: "Generator Starter", sw: "Mwashaji Jenereta" },
  { en: "Public Phone Operator", sw: "Mfanyakazi Simu za Umma" },
  { en: "Kiosk Guard", sw: "Mlinzi Kiosk" },
  { en: "Fence Watch", sw: "Mlinzi Ua" },
  { en: "Mat Seller", sw: "Muuzaji Mikeka" },
  { en: "Prayer Mat Washer", sw: "Mosha Mikeka ya Sala" },
  { en: "Mosque Cleaner", sw: "Msafishaji Msikiti" },
  { en: "Church Cleaner", sw: "Msafishaji Kanisa" },
  { en: "Street Sweeper (Morning)", sw: "Mfagia Barabara (Asubuhi)" },
  { en: "Street Sweeper (Evening)", sw: "Mfagia Barabara (Jioni)" },
  { en: "Market Cleaner", sw: "Msafishaji Soko" },
  { en: "Village Notice Distributor", sw: "Mgawaji Matangazo ya Kijiji" },
  { en: "Manual Announcement Crier", sw: "Mtangaza wa Mdomo" },
  { en: "Bell Ringer", sw: "Mpigaji Kengele" },
  { en: "Drum Beater (Announcer)", sw: "Mpigaji Ngoma (Mtangaza)" },
  { en: "Rain Shield Holder", sw: "Mshikaji Kinga ya Mvua" },
  { en: "Shoe Seller", sw: "Muuzaji Viatu" },
  { en: "Used Clothes Seller", sw: "Muuzaji Nguo za Mtumba" },
  { en: "Mobile Nail Technician", sw: "Fundi Kucha (Mzunguko)" },
  { en: "Online Video Commentator", sw: "Mtoaji Maoni Video Mtandaoni" },
  { en: "Facebook Live Helper", sw: "Msaidizi Facebook Live" },
  { en: "Instagram DM Responder", sw: "Mjibu Instagram DM" },
  { en: "Sticker Paster", sw: "Mbandikaji Stika" },
  { en: "Tin Cutter", sw: "Mkataji Bati" },
  { en: "Plastic Melter (Recycling)", sw: "Myeyushaji Plastiki (Uchakataji)" },
  { en: "Scrap Sorter", sw: "Mpangaji Taka za Chuma" },
  { en: "Plastic Sorter", sw: "Mpangaji Plastiki" },
  { en: "Metal Sorter", sw: "Mpangaji Madini" },
  { en: "Street-Level Data Collector", sw: "Mkusanyaji Data Mitaani" },
  { en: "Poll Assistant", sw: "Msaidizi Uchaguzi" },
  { en: "Political Campaign Helper", sw: "Msaidizi Kampeni za Kisiasa" },
  { en: "Public Survey Helper", sw: "Msaidizi Utafiti wa Umma" },
  { en: "Crowd Mobilizer", sw: "Mkusanyaji Umati" },
  { en: "Line Organizer", sw: "Mpangaji Foleni" },
  { en: "Local Stage Crew", sw: "Timu ya Jukwaa la Mitaa" },
  { en: "Video Booth Assistant", sw: "Msaidizi Kibanda cha Video" },
  { en: "Mirror Cleaner", sw: "Msafishaji Miwani" },
  { en: "Window Cleaner", sw: "Msafishaji Madirisha" },
  { en: "Gas Stove Cleaner", sw: "Msafishaji Jiko la Gesi" },
  { en: "Ceiling Fan Cleaner", sw: "Msafishaji Punkah" },
  { en: "Roof Sweeper", sw: "Mfagia Paa" },
  { en: "Yard Sweeper", sw: "Mfagia Uwanja" },
  { en: "Grass Cutter", sw: "Mkataji Nyasi" },
  { en: "Mop Assistant", sw: "Msaidizi Mop" },
  { en: "Rainwater Collector", sw: "Mkusanyaji Maji ya Mvua" },
  { en: "Cattle Feeder", sw: "Mlishaji Ng'ombe" },
  { en: "Cow Milker", sw: "Mkamaji Maziwa" },
  { en: "Milk Seller", sw: "Muuzaji Maziwa" },
  { en: "Milk Packager", sw: "Mfungaji Maziwa" },
  { en: "Milking Assistant", sw: "Msaidizi Ukamaji" },
  { en: "Job Category", sw: "Kategoria ya Kazi" },
  { en: "Baby Clothes Seller", sw: "Muuzaji Nguo za Watoto" },
  { en: "Used Shoe Seller", sw: "Muuzaji Viatu vya Mtumba" },
  { en: "Mobile Fruit Seller", sw: "Muuzaji Matunda (Mzunguko)" },
  { en: "Cassava Fryer", sw: "Mkaangaji Muhogo" },
  { en: "Banana Roaster", sw: "Mchomaji Ndizi" },
  { en: "Sweet Potato Seller", sw: "Muuzaji Viazi Vitamu" },
  { en: "Groundnut Roaster", sw: "Mkaangaji Karanga" },
  { en: "Popcorn Packer", sw: "Mfungaji Popcorn" },
  { en: "Samosa Seller", sw: "Muuzaji Samosa" },
  { en: "Egg Vendor", sw: "Muuzaji Mayai" },
  { en: "Street Tea Seller", sw: "Muuzaji Chai Barabara" },
  { en: "Coffee Thermos Seller", sw: "Muuzaji Kahawa ya Thermos" },
  { en: "Watermelon Slicer", sw: "Mkataji Tikiti Maji" },
  { en: "Coconut Opener", sw: "Mfunguaji Nazi" },
  { en: "Coconut Seller", sw: "Muuzaji Nazi" },
  { en: "Sugarcane Cutter", sw: "Mkataji Miwa" },
  { en: "Sugarcane Seller", sw: "Muuzaji Miwa" },
  { en: "Milk Tea Seller", sw: "Muuzaji Chai ya Maziwa" },
  { en: "Ice Water Seller", sw: "Muuzaji Maji Baridi" },
  { en: "Plastic Chair Rental", sw: "Ukodishaji Viti vya Plastiki" },
  { en: "Tent Rental", sw: "Ukodishaji Mahema" },
  { en: "Sound System Rental", sw: "Ukodishaji Mfumo wa Sauti" },
  { en: "Uniform Washer", sw: "Mosha Sare" },
  { en: "School Uniform Seller", sw: "Muuzaji Sare za Shule" },
  { en: "Plastic Bowl Seller", sw: "Muuzaji Bakuli za Plastiki" },
  { en: "Phone Card Seller", sw: "Muuzaji Kadi za Simu" },
  { en: "Battery Seller", sw: "Muuzaji Betri" },
  { en: "Umbrella Seller", sw: "Muuzaji Mivuli" },
  { en: "Raincoat Seller", sw: "Muuzaji Koti za Mvua" },
  { en: "Torch Battery Seller", sw: "Muuzaji Betri za Tochi" },
  { en: "Mirror Seller", sw: "Muuzaji Miwani" },
  { en: "Cooking Stick Seller", sw: "Muuzaji Vijiti vya Kupikia" },
  { en: "Wooden Spoon Seller", sw: "Muuzaji Vijiko vya Mbao" },
  { en: "Handmade Broom Seller", sw: "Muuzaji Ufagio wa Mkono" },
  { en: "Local Soap Maker", sw: "Mtengenezaji Sabuni wa Kimtaa" },
  { en: "Laundry Soap Seller", sw: "Muuzaji Sabuni ya Dobi" },
  { en: "Shoe Lace Seller", sw: "Muuzaji Kamba za Viatu" },
  { en: "Shoe Brush Seller", sw: "Muuzaji Brashi za Viatu" },
  { en: "Matchbox Seller", sw: "Muuzaji Kiberiti" },
  { en: "Toothpick Seller", sw: "Muuzaji Kijiti cha Meno" },
  { en: "Toothbrush Seller", sw: "Muuzaji Brashi za Meno" },
  { en: "Toothpaste Seller", sw: "Muuzaji Dawa ya Meno" },
  { en: "Sanitary Pad Seller", sw: "Muuzaji Pedi za Hedhi" },
  { en: "Diaper Seller", sw: "Muuzaji Nepi" },
  { en: "Powder Seller", sw: "Muuzaji Unga wa Kupaka" },
  { en: "Baby Oil Seller", sw: "Muuzaji Mafuta ya Watoto" },
  { en: "Combs Seller", sw: "Muuzaji Kitana" },
  { en: "Razor Blade Seller", sw: "Muuzaji Wembe" },
  { en: "Vaseline Seller", sw: "Muuzaji Vaseline" },
  { en: "Street DJ", sw: "DJ wa Barabara" },
  { en: "Portable Speaker DJ", sw: "DJ wa Spika za Kubeba" },
  { en: "Local Event Hype Man", sw: "Mchochezi Hafla za Mtaa" },
  { en: "Dancer (Traditional)", sw: "Mchezaji (Jadi)" },
  { en: "Gospel Singer (Small Gigs)", sw: "Mwimbaji Injili (Hafla Ndogo)" },
  { en: "Funeral Helper", sw: "Msaidizi Mazishi" },
  { en: "Burial Ceremony Setup", sw: "Mwandaji Sherehe za Mazishi" },
  { en: "Grave Digger Assistant", sw: "Msaidizi Mchimbaji Kaburi" },
  { en: "Village Church Usher", sw: "Muongozaji Kanisa la Kijiji" },
  { en: "Village Mosque Helper", sw: "Msaidizi Msikiti wa Kijiji" },
  { en: "Shoe Organizer (Religious)", sw: "Mpangaji Viatu (Dini)" },
  { en: "Koran Class Helper", sw: "Msaidizi Darasa la Kurani" },
  { en: "Bible Study Assistant", sw: "Msaidizi Utafiti wa Biblia" },
  { en: "Sunday School Assistant", sw: "Msaidizi Shule ya Jumapili" },
  { en: "Charcoal Stove Cleaner", sw: "Msafishaji Jiko la Mkaa" },
  { en: "Charcoal Seller", sw: "Muuzaji Mkaa" },
  { en: "Street Hawker (General)", sw: "Muuzaji Barabara (Jumla)" },
  { en: "Street Toy Seller", sw: "Muuzaji Michezo Barabara" },
  { en: "Mobile Toy Repairer", sw: "Mkarabati Michezo (Mzunguko)" },
  { en: "Book Seller", sw: "Muuzaji Vitabu" },
  { en: "Used Books Seller", sw: "Muuzaji Vitabu vya Mtumba" },
  { en: "Notebook Seller", sw: "Muuzaji Daftari" },
  { en: "Pen Seller", sw: "Muuzaji Kalamu" },
  { en: "Chalk Seller", sw: "Muuzaji Chaki" },
  { en: "Street Board Writer", sw: "Mwandishi Ubao Barabara" },
  { en: "Billboard Cleaner", sw: "Msafishaji Bango la Matangazo" },
  { en: "Sticker Remover", sw: "Mng'oaji Stika" },
  { en: "Phone Stand Seller", sw: "Muuzaji Viweko vya Simu" },
  { en: "Local Phone Case Maker", sw: "Mtengenezaji Kapu za Simu" },
  { en: "Shoelace Braider", sw: "Msokotaji Kamba za Viatu" },
  { en: "Plastic Repair Helper", sw: "Msaidizi Ukarabati Plastiki" },
  { en: "Clay Pot Moulder", sw: "Mfinyangaji Vyungu vya Udongo" },
  { en: "Sand Carrier", sw: "Mbebaji Mchanga" },
  { en: "Gravel Spreader", sw: "Mtandazaji Kokoto" },
  { en: "Water Tank Cleaner", sw: "Msafishaji Tanki la Maji" },
  { en: "Sewage Assistant", sw: "Msaidizi Maji Taka" },
  { en: "Pit Digger", sw: "Mchimbaji Shimo" },
  { en: "Manual Toilet Digger", sw: "Mchimbaji Choo cha Mkono" },
  { en: "Septic Tank Opener", sw: "Mfunguaji Tanki la Taka" },
  { en: "Mobile Fuel Seller", sw: "Muuzaji Mafuta (Mzunguko)" },
  { en: "Fuel Can Carrier", sw: "Mbebaji Kopo la Mafuta" },
  { en: "Generator Fuel Assistant", sw: "Msaidizi Mafuta ya Jenereta" },
  { en: "Construction Stone Breaker", sw: "Mvunjaji Mawe ya Ujenzi" },
  { en: "Sand Sifter", sw: "Mchujaji Mchanga" },
  { en: "Block Layer Assistant", sw: "Msaidizi Mwekaji Bloko" },
  { en: "Wheelbarrow Pusher", sw: "Msukumaji Mkokoteni" },
  { en: "Cement Bag Lifter", sw: "Minuaji Mifuko ya Saruji" },
  { en: "Rake User", sw: "Mtumiaji Jembe Dogo" },
  { en: "Hoe User", sw: "Mtumiaji Jembe" },
  { en: "Spade Helper", sw: "Msaidizi Koleo" },
  { en: "Fertilizer Spreader", sw: "Mtandazaji Mbolea" },
  { en: "Compost Turner", sw: "Mzungushaji Mbolea ya Asili" },
  { en: "Pig Feeder", sw: "Mlishaji Nguruwe" },
  { en: "Pig Sty Cleaner", sw: "Msafishaji Banda la Nguruwe" },
  { en: "Goat Cleaner", sw: "Msafishaji Mbuzi" },
  { en: "Dog Feeder", sw: "Mlishaji Mbwa" },
  { en: "Kennel Cleaner", sw: "Msafishaji Banda la Mbwa" },
  { en: "Chicken Vaccinator", sw: "Mpiga Sindano Kuku" },
  { en: "Cage Builder", sw: "Mjenzi Tundu" },
  { en: "Local Bricklayer", sw: "Mwekaji Matofali wa Kimtaa" },
  { en: "Water Distributor (Jug/Cart)", sw: "Mgawaji Maji (Mtungi/Mkokoteni)" },
  { en: "Well Digger", sw: "Mchimbaji Kisima" },
  { en: "Borehole Assistant", sw: "Msaidizi Kisima cha Kuchimba" },
  { en: "Rope Tyer", sw: "Mfunga Kamba" },
  { en: "Basket Weaver", sw: "Msokotaji Vikapu" },
  { en: "Mat Weaver", sw: "Msokotaji Mikeka" },
  { en: "Hand Fan Maker", sw: "Mtengenezaji Kipepeo cha Mkono" },
  { en: "Bead Maker", sw: "Mtengenezaji Ushanga" },
  { en: "Local Bracelet Seller", sw: "Muuzaji Bangili za Kimtaa" },
  { en: "Plastic Jewelry Seller", sw: "Muuzaji Vito vya Plastiki" },
  { en: "Bag Stitcher", sw: "Mshonaji Mifuko" },
  { en: "Mat Repairer", sw: "Mkarabati Mikeka" },
  { en: "Cloth Patch Expert", sw: "Fundi Kiraka za Nguo" },
  { en: "Small Iron Fixer", sw: "Mkarabati Pasi Ndogo" },
  { en: "Petrol Smell Remover", sw: "Mng'oaji Harufu ya Petroli" },
  { en: "Local Tour Guide (Village)", sw: "Mwongozaji wa Kimtaa (Kijiji)" },
  { en: "Bike Sharer", sw: "Mgawanaji Baiskeli" },
  { en: "Manual Cart Pusher", sw: "Msukumaji Mkokoteni wa Mkono" },
  { en: "Corn Grinder Operator", sw: "Mfanyakazi Kisaga Mahindi" },
  { en: "Maize Roaster", sw: "Mchomaji Mahindi" },
  { en: "Cassava Flour Seller", sw: "Muuzaji Unga wa Muhogo" },
  { en: "Tomato Packer", sw: "Mfungaji Nyanya" },
  { en: "Vegetable Sorter", sw: "Mpangaji Mboga" },
  { en: "Spice Seller", sw: "Muuzaji Viungo" },
  { en: "Salt Repacker", sw: "Mfungaji Chumvi" },
  { en: "Small Shop Watchman", sw: "Mlinzi Duka Dogo" },
  { en: "Door-to-door Milk Seller", sw: "Muuzaji Maziwa Nyumba kwa Nyumba" },
  { en: "Herbal Seller", sw: "Muuzaji Mitishamba" },
  { en: "Herbal Mixer", sw: "Mchanganyaji Mitishamba" },
  { en: "Local Doctor Assistant", sw: "Msaidizi Daktari wa Kimtaa" },
  {
    en: "Swahili Literacy Helper",
    sw: "Msaidizi Kusoma na Kuandika Kiswahili",
  },
  { en: "Adult Education Assistant", sw: "Msaidizi Elimu ya Watu Wazima" },
  { en: "Traditional Midwife Assistant", sw: "Msaidizi Mkunga wa Jadi" },
  { en: "Drum Carrier", sw: "Mbebaji Ngoma" },
  { en: "Cow Horn Cleaner", sw: "Msafishaji Pembe za Ng'ombe" },
  { en: "Street Music Performer", sw: "Mchezaji Muziki wa Barabara" },
  { en: "Rubbish Picker", sw: "Mchaguzi Takataka" },
  { en: "Used Paper Collector", sw: "Mkusanyaji Karatasi za Mtumba" },
  { en: "Palm Leaf Broom Maker", sw: "Mtengenezaji Ufagio wa Majani ya Mnazi" },
  { en: "Road Repair Helper", sw: "Msaidizi Ukarabati Barabara" },
  { en: "Pothole Marker", sw: "Mwekaji Alama Mashimo" },
  { en: "Reflector Holder", sw: "Mshikaji Kioo cha Kuakisi" },
  { en: "Manual Traffic Assistant", sw: "Msaidizi Trafiki wa Mkono" },
  { en: "Truck Wash Helper", sw: "Msaidizi Kuosha Malori" },
  { en: "Matress Beater", sw: "Mpigaji Godoro" },
  { en: "Foam Cutter", sw: "Mkataji Povu" },
  { en: "Rubber Sorter", sw: "Mpangaji Mpira" },
  { en: "Plastic Shredder", sw: "Mchanjaji Plastiki" },
  { en: "Aluminum Collector", sw: "Mkusanyaji Alumini" },
  { en: "Scrap Iron Seller", sw: "Muuzaji Chuma Taka" },
  { en: "Wire Straightener", sw: "Mnyooshaji Waya" },
  { en: "Rope Seller", sw: "Muuzaji Kamba" },
  { en: "Cement Mixer Operator", sw: "Mfanyakazi Kichanja Saruji" },
  { en: "Construction Timer Caller", sw: "Mpigaji Saa Ujenzi" },
  { en: "Shovel Washer", sw: "Mosha Koleo" },
  { en: "Concrete Block Turner", sw: "Mzungushaji Bloko za Saruji" },
  { en: "Temporary Store Watch", sw: "Mlinzi Duka la Muda" },
  { en: "Road Sign Carrier", sw: "Mbebaji Vibao vya Barabara" },
  { en: "Welding Wire Cleaner", sw: "Msafishaji Waya za Kuyunganisha" },
  { en: "Mobile Kiosk Setup Helper", sw: "Msaidizi Kuweka Kiosk ya Kuzunguka" },
  { en: "Phone Charging Assistant", sw: "Msaidizi Kuchaji Simu" },
  { en: "Power Extension Seller", sw: "Muuzaji Extension za Umeme" },
  { en: "Local Time Caller", sw: "Mpigaji Saa wa Kimtaa" },
  { en: "Rain Watch Informant", sw: "Mtoaji Taarifa za Mvua" },
  { en: "Child Escorter (to school)", sw: "Mzungumzaji Watoto (Shuleni)" },
  { en: "Market Basket Watch", sw: "Mlinzi Kikapu Sokoni" },
  { en: "Farm Tools Cleaner", sw: "Msafishaji Vifaa vya Kilimo" },
  { en: "Seed Sorter", sw: "Mpangaji Mbegu" },
  { en: "Fertilizer Bagger", sw: "Mfungaji Mbolea" },
  { en: "Yam Peeler", sw: "Mmebuzi Viazi Vikuu" },
  { en: "Cassava Peeler", sw: "Mmebuzi Muhogo" },
  { en: "Onion Peeler", sw: "Mmebuzi Vitunguu" },
  { en: "Tomato Cutter", sw: "Mkataji Nyanya" },
  { en: "Vegetable Chopper", sw: "Mkatakataji Mboga" },
  { en: "Fish Scaler", sw: "Mng'oaji Magamba ya Samaki" },
  { en: "Meat Cutter", sw: "Mkataji Nyama" },
  { en: "Goat Skin Peeler", sw: "Mmebuzi Ngozi za Mbuzi" },
  { en: "Cow Head Burner", sw: "Mchomaji Kichwa cha Ng'ombe" },
  { en: "Slaughterhouse Helper", sw: "Msaidizi Machinjio" },
  { en: "Fish Seller", sw: "Muuzaji Samaki" },
  { en: "Kuku Seller", sw: "Muuzaji Kuku" },
  { en: "Cow Hoof Scraper", sw: "Mkodoaji Kwapa za Ng'ombe" },
  { en: "Choma Assistant", sw: "Msaidizi Choma" },
  { en: "Fruit Waste Collector", sw: "Mkusanyaji Taka za Matunda" },
  { en: "Food Plate Washer (Events)", sw: "Mosha Sahani (Hafla)" },
  { en: "Food Packager (Events)", sw: "Mfungaji Chakula (Hafla)" },
  { en: "Street Crowd Organizer", sw: "Mpangaji Umati wa Barabara" },
  { en: "Drunk Escorter (Safety)", sw: "Mzungumzaji Walevi (Usalama)" },
  { en: "Lost Child Finder", sw: "Mtafutaji Watoto Waliopotea" },
  { en: "Street Candle Seller", sw: "Muuzaji Mishumaa Barabara" },
  { en: "Flashlight Seller", sw: "Muuzaji Tochi" },
  { en: "Soap Foam Sprayer", sw: "Mnyunyizi Povu la Sabuni" },
  { en: "Spit Guard Cleaner", sw: "Msafishaji Kinga za Mate" },
  { en: "Bench Rental", sw: "Ukodishaji Viti vya Mbao" },
  { en: "Basin Rental", sw: "Ukodishaji Karai" },
  { en: "Local Canoe Assistant", sw: "Msaidizi Mtumbwi wa Kimtaa" },
  { en: "Beach Cleaner", sw: "Msafishaji Ufuo" },
  { en: "Coconut Oil Seller", sw: "Muuzaji Mafuta ya Nazi" },
  { en: "Palm Wine Tapper", sw: "Mchongaji Tembo" },
  { en: "Local Brew Seller", sw: "Muuzaji Pombe za Kimtaa" },
  { en: "Local Brew Guard", sw: "Mlinzi Pombe za Kimtaa" },
  { en: "Street Begging Companion", sw: "Mwenzangu Kuomba Barabara" },
  { en: "Blind Person Guide", sw: "Mwongozaji Kipofu" },
  { en: "Wheelchair Pusher", sw: "Msukumaji Kiti cha Magurudumu" },
  { en: "Market Bell Ringer", sw: "Mpigaji Kengele Sokoni" },
  { en: "Traditional Healer Assistant", sw: "Msaidizi Mganga wa Jadi" },
  { en: "Drum Stick Seller", sw: "Muuzaji Fimbo za Ngoma" },
  { en: "Beaded Necklace Seller", sw: "Muuzaji Mikufu ya Ushanga" },
  { en: "Children Toy Balloon Blower", sw: "Mvimbaji Maputo ya Michezo" },
  { en: "Street Performer Assistant", sw: "Msaidizi Mchezaji wa Barabara" },
  { en: "Funeral Cloth Seller", sw: "Muuzaji Vitenge vya Mazishi" },
  { en: "Wedding Cloth Assistant", sw: "Msaidizi Vitenge vya Harusi" },
  { en: "Aso-Ebi Seller", sw: "Muuzaji Aso-Ebi" },
  { en: "Traditional Cloth Folder", sw: "Mkunjaji Vitenge vya Jadi" },
  { en: "Security Reflector Seller", sw: "Muuzaji Vioo vya Ulinzi" },
  { en: "Safety Boot Seller", sw: "Muuzaji Viatu vya Usalama" },
  { en: "Umbrella Sharer (Rainy Days)", sw: "Mgawanaji Mivuli (Siku za Mvua)" },
  { en: "Rain Coat Sharer", sw: "Mgawanaji Koti za Mvua" },
  { en: "Plastic Slipper Seller", sw: "Muuzaji Vilatu vya Plastiki" },
  { en: "School Sandal Seller", sw: "Muuzaji Viatu vya Shule" },
  { en: "Morning Alarm Caller", sw: "Mpigaji Kengele ya Asubuhi" },
  { en: "Evening Watch Caller", sw: "Mpigaji Kengele ya Jioni" },
  { en: "Job Category", sw: "Kategoria ya Kazi" },
  { en: "Private Chef", sw: "Mpishi Binafsi" },
  { en: "Personal Driver", sw: "Dereva Binafsi" },
  { en: "Chauffeur", sw: "Dereva wa Hali ya Juu" },
  { en: "Nanny (Live-in)", sw: "Mlezi (Anaokaa Nyumbani)" },
  {
    en: "Private Tutor (English/French)",
    sw: "Mwalimu Binafsi (Kiingereza/Kifaransa)",
  },
  { en: "Home School Teacher", sw: "Mwalimu wa Shule ya Nyumbani" },
  { en: "Gardener (Private Estate)", sw: "Mbustani (Makazi ya Binafsi)" },
  { en: "House Manager", sw: "Meneja wa Nyumba" },
  { en: "Villa Cleaner", sw: "Msafishaji Villa" },
  { en: "Butler", sw: "Mhudumu Mkuu" },
  { en: "Valet (Private Events)", sw: "Mhudumu (Hafla za Binafsi)" },
  { en: "Private Security Guard", sw: "Askari wa Ulinzi Binafsi" },
  { en: "Gate Keeper", sw: "Mlinzi Lango" },
  { en: "CCTV Monitor Assistant", sw: "Msaidizi Mfuatiliaji CCTV" },
  { en: "Pool Cleaner", sw: "Msafishaji Bwawa" },
  { en: "Home Bar Attendant", sw: "Mhudumu Baa ya Nyumbani" },
  { en: "Wine Cellar Assistant", sw: "Msaidizi Ghala la Divai" },
  { en: "Home Organizer", sw: "Mpangaji Nyumba" },
  { en: "Wardrobe Assistant", sw: "Msaidizi Kabati la Nguo" },
  { en: "Stylist Assistant", sw: "Msaidizi Mtayarishaji Mavazi" },
  { en: "Fashion Consultant", sw: "Mshauri Mitindo" },
  { en: "Massage Therapist (Private)", sw: "Fundi Massage (Binafsi)" },
  { en: "Hair Stylist (Private Home)", sw: "Msusi Nywele (Nyumba ya Binafsi)" },
  { en: "Makeup Artist (Private)", sw: "Fundi Vipodozi (Binafsi)" },
  { en: "Spa Therapist (Mobile)", sw: "Fundi Spa (Mzunguko)" },
  {
    en: "Yoga Instructor (Home Service)",
    sw: "Mwalimu Yoga (Huduma ya Nyumbani)",
  },
  {
    en: "Personal Trainer (Home Gym)",
    sw: "Mwalimu wa Afya (Gym ya Nyumbani)",
  },
  { en: "Dog Walker", sw: "Mtembezaji Mbwa" },
  { en: "Pet Groomer", sw: "Msafishaji Wanyamapori" },
  { en: "Pet Feeder", sw: "Mlishaji Wanyamapori" },
  {
    en: "Pet Sitter (Travel Periods)",
    sw: "Mlezi Wanyamapori (Wakati wa Safari)",
  },
  { en: "Aquarium Cleaner", sw: "Msafishaji Mfuko wa Samaki" },
  { en: "Interior Decor Assistant", sw: "Msaidizi Mapambo ya Ndani" },
  { en: "Home Theater Technician", sw: "Fundi Sinema ya Nyumbani" },
  { en: "Smart Home Assistant", sw: "Msaidizi Nyumba ya Kisasa" },
  {
    en: "Private Event Planner Assistant",
    sw: "Msaidizi Mpangaji Hafla za Binafsi",
  },
  { en: "Private Event Server", sw: "Mhudumu Hafla za Binafsi" },
  { en: "Waiter (Luxury Event)", sw: "Mhudumu (Hafla za Anasa)" },
  { en: "Barman (Private Party)", sw: "Mhudumu Baa (Sherehe za Binafsi)" },
  { en: "Barista (Home Setup)", sw: "Mtengenezaji Kahawa (Nyumbani)" },
  { en: "Live Band Assistant", sw: "Msaidizi Bendi ya Moja kwa Moja" },
  { en: "Personal Shopper", sw: "Mnunuzi Binafsi" },
  { en: "Luxury Errand Runner", sw: "Mtumishi Ujumbe wa Anasa" },
  { en: "Parcel Handler (Private)", sw: "Mshughulikia Vifurushi (Binafsi)" },
  { en: "Luggage Organizer", sw: "Mpangaji Mizigo" },
  { en: "Closet Organizer", sw: "Mpangaji Kabati" },
  { en: "Laundry Folder", sw: "Mkunjaji Nguo za Dobi" },
  { en: "Ironing Expert", sw: "Fundi Kupiga Pasi" },
  { en: "Car Detailer", sw: "Msafishaji Magari kwa Undani" },
  { en: "Motorcycle Detailer", sw: "Msafishaji Pikipiki kwa Undani" },
  { en: "Yard Maintenance Supervisor", sw: "Msimamizi Utunzaji Uwanja" },
  { en: "Flower Bed Maintainer", sw: "Mtunza Bustani ya Maua" },
  { en: "Greenhouse Assistant", sw: "Msaidizi Nyumba ya Kioo" },
  { en: "Landscaping Assistant", sw: "Msaidizi Upangaji Mazingira" },
  {
    en: "Tree Trimmer (Private Compound)",
    sw: "Mkataji Miti (Uwanja wa Binafsi)",
  },
  {
    en: "Window Cleaner (Double Story)",
    sw: "Msafishaji Madirisha (Ghorofa Mbili)",
  },
  { en: "Chandelier Cleaner", sw: "Msafishaji Taa za Mapambo" },
  { en: "Shoe Organizer", sw: "Mpangaji Viatu" },
  { en: "Luxury Furniture Polisher", sw: "Msuguzi Samani za Anasa" },
  { en: "High-end Appliance Cleaner", sw: "Msafishaji Vifaa vya Hali ya Juu" },
  { en: "Silverware Polisher", sw: "Msuguzi Vyombo vya Fedha" },
  { en: "Crystal Cleaner", sw: "Msafishaji Kioo cha Johari" },
  {
    en: "Dishwasher (Fine Dining Events)",
    sw: "Mosha Vyombo (Hafla za Chakula Bora)",
  },
  { en: "Porcelain Handler", sw: "Mshughulikia Vyombo vya Udongo Mzuri" },
  { en: "Curtain Installer", sw: "Mwekaji Mapazia" },
  { en: "Curtain Cleaner (Manual)", sw: "Msafishaji Mapazia (Kwa Mkono)" },
  { en: "Air Conditioner Cleaner", sw: "Msafishaji Kifaa cha Hewa" },
  {
    en: "Pest Control Assistant (Home)",
    sw: "Msaidizi Udhibiti Wadudu (Nyumbani)",
  },
  {
    en: "Garbage Manager (Luxury Homes)",
    sw: "Meneja Takataka (Nyumba za Anasa)",
  },
  { en: "Backup Generator Operator", sw: "Mfanyakazi Jenereta ya Hifadhi" },
  { en: "Solar Panel Cleaner", sw: "Msafishaji Paneli za Jua" },
  { en: "Elevator Operator (Mansion)", sw: "Mfanyakazi Elevator (Jumba)" },
  {
    en: "Tech Setup Assistant (TVs, WiFi, Speakers)",
    sw: "Msaidizi Kuweka Teknolojia (TV, WiFi, Spika)",
  },
  {
    en: "Home WiFi Troubleshooter",
    sw: "Mtatuzi Matatizo ya WiFi ya Nyumbani",
  },
  { en: "CCTV Installer Assistant", sw: "Msaidizi Mwekaji CCTV" },
  { en: "Garage Organizer", sw: "Mpangaji Garage" },
  { en: "Workshop Cleaner", sw: "Msafishaji Warsha" },
  { en: "Private Gym Cleaner", sw: "Msafishaji Gym ya Binafsi" },
  { en: "Home Library Organizer", sw: "Mpangaji Maktaba ya Nyumbani" },
  { en: "Art Dusting Assistant", sw: "Msaidizi Kuondoa Vumbi Sanaa" },
  { en: "Valuable Item Cleaner", sw: "Msafishaji Vitu vya Thamani" },
  { en: "Safe Room Cleaner", sw: "Msafishaji Chumba cha Usalama" },
  { en: "Fish Tank Cleaner", sw: "Msafishaji Tanki la Samaki" },
  { en: "Wine Rack Organizer", sw: "Mpangaji Rafu la Divai" },
  { en: "Pet House Cleaner", sw: "Msafishaji Nyumba ya Wanyamapori" },
  { en: "Shoe Shiner (Luxury Shoes)", sw: "Msuguzi Viatu (Viatu vya Anasa)" },
  {
    en: "Ironing Specialist (Luxury Clothes)",
    sw: "Fundi Kupiga Pasi (Nguo za Anasa)",
  },
  { en: "Delicate Fabric Handler", sw: "Mshughulikia Nguo za Laini" },
  { en: "Luxury Bag Cleaner", sw: "Msafishaji Mifuko ya Anasa" },
  { en: "Private Errand Person", sw: "Mtu wa Ujumbe Binafsi" },
  {
    en: "Dry Cleaner Pickup Assistant",
    sw: "Msaidizi Kuchukua Nguo za Kukaushia",
  },
  {
    en: "Private Airport Transfer Assistant",
    sw: "Msaidizi Usafirishaji Uwanja wa Ndege Binafsi",
  },
  { en: "Luxury Car Washer", sw: "Mosha Magari ya Anasa" },
  { en: "Luxury Car Driver", sw: "Dereva Magari ya Anasa" },
  { en: "Security Driver (Armored)", sw: "Dereva Ulinzi (wa Chuma)" },
  { en: "School Driver for Kids", sw: "Dereva Shule kwa Watoto" },
  { en: "Doctor Appointment Companion", sw: "Mwenzangu Miadi ya Daktari" },
  { en: "Grocery Organizer", sw: "Mpangaji wa Vyakula" },
  { en: "Pantry Organizer", sw: "Mpangaji wa Hifadhi ya Vyakula" },
  { en: "Meal Prep Assistant", sw: "Msaidizi Maandalizi ya Chakula" },
  { en: "Grocery Organizer", sw: "Mpangaji wa Vyakula" },
  { en: "Pantry Organizer", sw: "Mpangaji wa Hifadhi ya Vyakula" },
  { en: "Meal Prep Assistant", sw: "Msaidizi wa Maandalizi ya Chakula" },
  { en: "Table Setter (Formal Dining)", sw: "Mwekaji Meza (Chakula Rasmi)" },
  { en: "Dining Assistant", sw: "Msaidizi wa Chakula" },
  { en: "Butcher (Home Slaughter)", sw: "Mchinjaji (Nyumbani)" },
  { en: "Home BBQ Chef", sw: "Mpishi wa BBQ Nyumbani" },
  { en: "Private Sushi Chef", sw: "Mpishi wa Sushi Binafsi" },
  { en: "Diet Cook Assistant", sw: "Msaidizi wa Mpishi wa Lishe" },
  { en: "Nutrition Assistant", sw: "Msaidizi wa Lishe" },
  { en: "Juice Bar Assistant (Home)", sw: "Msaidizi wa Juisi Nyumbani" },
  { en: "Home Coffee Barista", sw: "Barista wa Kahawa Nyumbani" },
  {
    en: "Home Gym Equipment Cleaner",
    sw: "Msafishaji wa Vifaa vya Gym Nyumbani",
  },
  { en: "Steam Ironing Expert", sw: "Mtaalamu wa Kupiga Pasi kwa Mvuke" },
  { en: "Carpet Shampoo Expert", sw: "Mtaalamu wa Kusafisha Zulia" },
  {
    en: "Luxury Pet Toy Cleaner",
    sw: "Msafishaji wa Vifaa vya Wanyama wa Anasa",
  },
  { en: "Spa Water Assistant", sw: "Msaidizi wa Maji ya Spa" },
  { en: "Candle Setup Assistant", sw: "Msaidizi wa Kupanga Mishumaa" },
  { en: "Aromatherapy Assistant", sw: "Msaidizi wa Matibabu ya Harufu" },
  {
    en: "Event Decoration Assistant (Luxury)",
    sw: "Msaidizi wa Mapambo ya Tukio (Anasa)",
  },
  { en: "Luxury Gift Wrapper", sw: "Mfungaji wa Zawadi za Anasa" },
  { en: "Personal Courier", sw: "Mjumbe Binafsi" },
  {
    en: "Dry-Clean-Only Garment Handler",
    sw: "Mshughulikiaji wa Nguo za Kukausha Pekee",
  },
  { en: "Suit Organizer", sw: "Mpangaji wa Suti" },
  { en: "Home Office Assistant", sw: "Msaidizi wa Ofisi ya Nyumbani" },
  { en: "Laptop Cleaner", sw: "Msafishaji wa Kompyuta Mpya" },
  { en: "Tech Device Cleaner", sw: "Msafishaji wa Vifaa vya Teknolojia" },
  { en: "Tablet Organizer", sw: "Mpangaji wa Kompyuta Kibao" },
  { en: "Charging Station Setup", sw: "Mwekaji wa Kituo cha Kuchaji" },
  { en: "Eco-Lawn Sprayer", sw: "Mnyunyiziaji wa Nyasi za Mazingira" },
  { en: "Luxury Fragrance Organizer", sw: "Mpangaji wa Manukato ya Anasa" },
  {
    en: "Home Fragrance Diffuser Assistant",
    sw: "Msaidizi wa Kisambaza Harufu Nyumbani",
  },
  { en: "Closet Color Coordinator", sw: "Mpangaji wa Rangi Kabatini" },
  {
    en: "Child Travel Pack Assistant",
    sw: "Msaidizi wa Vifurushi vya Safari ya Mtoto",
  },
  { en: "Personal Wake-up Caller", sw: "Mpigaji Simu wa Kuamsha Binafsi" },
  { en: "Watch Organizer", sw: "Mpangaji wa Saa" },
  {
    en: "Private Safe Assistant",
    sw: "Msaidizi wa Sanduku la Usalama Binafsi",
  },
  { en: "Private Photo Organizer", sw: "Mpangaji wa Picha Binafsi" },
  {
    en: "Social Media Assistant (Personal Brand)",
    sw: "Msaidizi wa Mitandao ya Kijamii (Chapa Binafsi)",
  },
  {
    en: "Luxury Garden Decor Assistant",
    sw: "Msaidizi wa Mapambo ya Bustani ya Anasa",
  },
  {
    en: "Chauffeur Uniform Cleaner",
    sw: "Msafishaji wa Sare za Dereva wa Hali ya Juu",
  },
  {
    en: "High-Profile Party Staff",
    sw: "Wafanyakazi wa Sherehe za Hadhi ya Juu",
  },
  { en: "VIP Guest Handler", sw: "Mshughulikiaji wa Wageni wa VIP" },
  { en: "VIP Lounge Assistant", sw: "Msaidizi wa Sebule ya VIP" },
  { en: "Security Dog Handler", sw: "Mshughulikiaji wa Mbwa wa Ulinzi" },
  { en: "Patio Cleaner", sw: "Msafishaji wa Baraza" },
  { en: "Outdoor Furniture Washer", sw: "Mosha Samani za Nje" },
  { en: "Wood Polishing Assistant", sw: "Msaidizi wa Kusugua Mbao" },
  { en: "Luxury Rug Beater", sw: "Mpigaji Zulia la Anasa" },
  { en: "Outdoor Bar Setup Assistant", sw: "Msaidizi wa Kupanga Baa ya Nje" },
  { en: "Deck Cleaner", sw: "Msafishaji wa Ubao wa Nje" },
  { en: "Roof Gutter Cleaner", sw: "Msafishaji wa Mifereji ya Paa" },
  {
    en: "Private Dock Assistant (Lake houses)",
    sw: "Msaidizi wa Gati Binafsi (Nyumba za Ziwa)",
  },
  { en: "Jet Ski Cleaner", sw: "Msafishaji wa Jet Ski" },
  { en: "Golf Cart Cleaner", sw: "Msafishaji wa Gari la Gofu" },
  { en: "Golf Gear Assistant", sw: "Msaidizi wa Vifaa vya Gofu" },
  {
    en: "Equestrian Assistant (Horse Care)",
    sw: "Msaidizi wa Farasi (Utunzaji wa Farasi)",
  },
  {
    en: "Luxury Pet Walker (Dog breeds)",
    sw: "Mtembezaji wa Wanyama wa Anasa (Mbwa)",
  },
  {
    en: "Private Estate Tour Assistant",
    sw: "Msaidizi wa Ziara ya Mali Binafsi",
  },
  {
    en: "Drone Flight Assistant (Events)",
    sw: "Msaidizi wa Ndege ya Drone (Matukio)",
  },
  { en: "Kids’ Party Assistant", sw: "Msaidizi wa Sherehe za Watoto" },
  { en: "Pool Party Setup Crew", sw: "Timu ya Kupanga Sherehe ya Bwawa" },
  { en: "Luxury Tent Installer", sw: "Mwekaji wa Mahema ya Anasa" },
  { en: "Fountain Cleaner", sw: "Msafishaji wa Chemchemi" },
  { en: "Borehole Water Tester", sw: "Mjaribu wa Maji ya Kisima" },
  {
    en: "Water Tank Level Checker",
    sw: "Mwangalizi wa Kiwango cha Maji Tankini",
  },
  {
    en: "Private Generator Fuel Filler",
    sw: "Mjaza Mafuta ya Jenereta Binafsi",
  },
  { en: "Rain Sensor Tester", sw: "Mjaribu wa Kihisi cha Mvua" },
  { en: "Mosquito Net Installer", sw: "Mwekaji wa Chandarua" },
  {
    en: "Private Photographer Assistant",
    sw: "Msaidizi wa Mpiga Picha Binafsi",
  },
  { en: "Flower Arrangement Assistant", sw: "Msaidizi wa Kupanga Maua" },
  { en: "Home Scent Specialist", sw: "Mtaalamu wa Harufu ya Nyumbani" },
  {
    en: "Event Guest Usher (Luxury Events)",
    sw: "Muongozaji wa Wageni wa Tukio (Anasa)",
  },
  { en: "Portrait Dusting Expert", sw: "Mtaalamu wa Kuondoa Vumbi Picha" },
  { en: "Classic Record Organizer", sw: "Mpangaji wa Rekodi za Klasiki" },
  { en: "Cultural Decor Cleaner", sw: "Msafishaji wa Mapambo ya Kitamaduni" },
  { en: "Custom Light Controller", sw: "Mdhibiti wa Taa Maalum" },
  { en: "Mood Lighting Assistant", sw: "Msaidizi wa Taa za Hisia" },
  { en: "Small Biz Support", sw: "Msaada wa Biashara Ndogo" },
  { en: "Digital Microtasks", sw: "Kazi Ndogo za Kidijitali" },
  { en: "Creative Gigs", sw: "Kazi za Ubunifu" },
  { en: "Wellness Services", sw: "Huduma za Afya" },
  { en: "Green Jobs", sw: "Kazi za Mazingira" },
  { en: "Emergency Aid", sw: "Msaada wa Dharura" },
  { en: "Social Care", sw: "Huduma za Jamii" },
  { en: "Event Tech", sw: "Teknolojia ya Matukio" },
  { en: "Seasonal Help", sw: "Msaada wa Msimu" },
  { en: "Safety Compliance", sw: "Uzingatiaji wa Usalama" },
  { en: "Field Research", sw: "Utafiti wa Shambani" },
  { en: "Logistics Assist", sw: "Msaidizi wa Usafirishaji" },
  { en: "Home Crafts", sw: "Sanaa za Nyumbani" },
  { en: "Tutoring", sw: "Ualimu wa Binafsi" },
  { en: "Personal Development", sw: "Maendeleo Binafsi" },
  { en: "Elder Care", sw: "Huduma kwa Wazee" },
  { en: "School Support", sw: "Msaada wa Shule" },
  { en: "Campus Services", sw: "Huduma za Chuo" },
  { en: "Library Assist", sw: "Msaidizi wa Maktaba" },
  { en: "IT Support", sw: "Msaada wa IT" },
  { en: "Security Patrol", sw: "Doria ya Usalama" },
  { en: "Facilities Assist", sw: "Msaidizi wa Vifaa" },
  { en: "Student Transport", sw: "Usafiri wa Wanafunzi" },
  { en: "Admin Assist", sw: "Msaidizi wa Utawala" },
  { en: "Errand Running", sw: "Mbio za Ujumbe" },
  { en: "Pet Care", sw: "Huduma ya Wanyama" },
  { en: "Language Guide", sw: "Mwongozaji wa Lugha" },
  { en: "Wellness Check", sw: "Ukaguzi wa Afya" },
  { en: "Mystery Shop", sw: "Duka la Siri" },
  { en: "Custom Job", sw: "Kazi Maalum" },
];
