const env = import.meta.env;
const Env = {
  baseURL: env.VITE_BASE_URL,
  FIREBASE_API_KEY: env.VITE_FIREBASE_API,
  KEYCLOAK_CLIENT_ID: env.VITE_KEYCLOAK_CLIENT_ID,
  KEYCLOAK_ISSUER: env.VITE_KEYCLOAK_ISSUER,
  REFRESH_TOKEN_URL: env.VITE_REFRESH_TOKEN_URL,
  KEYCLOAK_URL: env.VITE_KEYCLOAK_URL,
  googleMapsApiKey: env.VITE_GOOGLE_MAPS_API_KEY,
  JWT_SECRET: env.VITE_JWT_SECRET,
  CHATBOT_URL: env.VITE_CHATBOT_URL,
  CHATBOT_ID: env.VITE_CHATBOT_ID,
  CHATBOT_ID_SENDER: env.VITE_CHATBOT_ID_SENDER,
  APP_VAPID_KEY: env.VITE_APP_VAPID_KEY,
};

export default Env;
