name: React Production CI

on:
  push:
    # branches: ["production"]
    branches: ["prod"]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: yarn install

    - name: Build React app with environment variables
      run: yarn build --mode production

    - name: Transfer build files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "dist/*"
        target: "/home/ubuntu/raiz/raiz-dashboard"

    - name: Deploy to production server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ubuntu/raiz/raiz-dashboard
          git add .
          git stash
          git pull origin deploy
          sudo docker compose -f docker-compose.prod.yml down
          sudo docker compose -f docker-compose.prod.yml up -d --build
